apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: risk-assessor-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dark5eid2021/project_janus.git'
    targetRevision: HEAD
    path: path/to/your/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
